name: linux

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        cxx: [g++-9, g++-10, clang++-10, clang++-12] # see below for clang-11
        build_type: [Debug, Release]
        std: [17, 20]
        os: [ubuntu-20.04]
        include:
          # Test GCC 11 on Ubuntu 18.04
          - cxx: g++-11
            std: 17
            build_type: Debug
            os: ubuntu-18.04
            install: sudo apt install g++-11
          - cxx: g++-11
            std: 17
            build_type: Release
            os: ubuntu-18.04
            install: sudo apt install g++-11
          - cxx: g++-11
            std: 20
            build_type: Debug
            os: ubuntu-18.04
            install: sudo apt install g++-11
          - cxx: g++-11
            std: 20
            build_type: Release
            os: ubuntu-18.04
            install: sudo apt install g++-11
          # Test Clang 9 on Ubuntu 18.04
          - cxx: clang++-9
            std: 17
            build_type: Debug
            os: ubuntu-18.04
          # Test Clang 11 with both libstdc++ and libc++
          - cxx: clang++-11
            std: 17
            build_type: Debug
            os: ubuntu-20.04
          - cxx: clang++-11
            std: 17
            build_type: Debug
            os: ubuntu-20.04
            cxx_flags: -stdlib=libc++
            install: sudo apt install libc++-11-dev libc++abi-11-dev
          - cxx: clang++-11
            std: 20
            build_type: Debug
            os: ubuntu-20.04
          - cxx: clang++-11
            std: 20
            build_type: Debug
            os: ubuntu-20.04
            cxx_flags: -stdlib=libc++
            install: sudo apt install libc++-11-dev libc++abi-11-dev
          - cxx: clang++-11
            std: 17
            build_type: Release
            os: ubuntu-20.04
          - cxx: clang++-11
            std: 17
            build_type: Release
            os: ubuntu-20.04
            cxx_flags: -stdlib=libc++
            install: sudo apt install libc++-11-dev libc++abi-11-dev
          - cxx: clang++-11
            std: 20
            build_type: Release
            os: ubuntu-20.04
          - cxx: clang++-11
            std: 20
            build_type: Release
            os: ubuntu-20.04
            cxx_flags: -stdlib=libc++
            install: sudo apt install libc++-11-dev libc++abi-11-dev

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: |
        ${{matrix.install}}
        cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure
      working-directory: ${{runner.workspace}}/build
      env:
        CXX: ${{matrix.cxx}}
        CXXFLAGS: ${{matrix.cxx_flags}}
      run: |
        cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}}  \
              -DCMAKE_CXX_STANDARD=${{matrix.std}}  \
              $GITHUB_WORKSPACE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config ${{matrix.build_type}} -- -j2

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: ctest -C ${{matrix.build_type}}
      env:
        CTEST_OUTPUT_ON_FAILURE: True
